/**
 * Comprehensive Test Data Seed Script
 * 
 * This script seeds the database with comprehensive test data to verify
 * all website functionality is working correctly.
 * 
 * Run with: npx ts-node --compiler-options '{"module":"commonjs"}' scripts/seed-test-data.ts
 * Or via API: POST /api/admin/seed-comprehensive
 */

import { FieldValue, Timestamp } from 'firebase-admin/firestore'

// Helper to create dates relative to now
const daysFromNow = (days: number) => {
  const d = new Date()
  d.setDate(d.getDate() + days)
  return d
}

const hoursFromNow = (hours: number) => {
  const d = new Date()
  d.setHours(d.getHours() + hours)
  return d
}

// ============================================================================
// TEAM MEMBERS (Board + Leadership)
// ============================================================================
export const TEST_TEAM_MEMBERS = [
  {
    id: 'president-2026',
    group: 'board',
    title: 'Club President',
    name: 'Alexandra Rivera',
    role: 'Leads the club and oversees all operations',
    photoUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&h=400&fit=crop',
    order: 1,
    active: true,
    bio: 'Finance professional with 5 years of Rotaract experience. Passionate about youth leadership development.',
    linkedin: 'https://linkedin.com/in/example',
    email: 'president@rotaractnyc.org',
  },
  {
    id: 'vice-president-2026',
    group: 'board',
    title: 'Vice President',
    name: 'Marcus Thompson',
    role: 'Assists the President and manages internal affairs',
    photoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop',
    order: 2,
    active: true,
    bio: 'Marketing strategist dedicated to expanding our club\'s reach and impact.',
  },
  {
    id: 'secretary-2026',
    group: 'board',
    title: 'Club Secretary',
    name: 'Jennifer Park',
    role: 'Handles communications and record-keeping',
    photoUrl: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&h=400&fit=crop',
    order: 3,
    active: true,
    bio: 'Detail-oriented professional ensuring our club runs smoothly.',
  },
  {
    id: 'treasurer-2026',
    group: 'board',
    title: 'Club Treasurer',
    name: 'David Chen',
    role: 'Manages finances and fundraising',
    photoUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&h=400&fit=crop',
    order: 4,
    active: true,
    bio: 'CPA with expertise in non-profit financial management.',
  },
  {
    id: 'service-chair-2026',
    group: 'board',
    title: 'Service Chair',
    name: 'Amara Okonkwo',
    role: 'Coordinates community service projects',
    photoUrl: 'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=400&h=400&fit=crop',
    order: 5,
    active: true,
    bio: 'Social worker committed to making tangible community impact.',
  },
  {
    id: 'membership-chair-2026',
    group: 'board',
    title: 'Membership Chair',
    name: 'Ryan Mitchell',
    role: 'Recruits and engages members',
    photoUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=400&fit=crop',
    order: 6,
    active: true,
    bio: 'HR professional focused on building an inclusive, engaged membership.',
  },
  {
    id: 'events-chair-2026',
    group: 'board',
    title: 'Events Chair',
    name: 'Sofia Martinez',
    role: 'Plans and executes club events',
    photoUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&h=400&fit=crop',
    order: 7,
    active: true,
    bio: 'Event planner extraordinaire bringing creative ideas to every gathering.',
  },
  {
    id: 'communications-chair-2026',
    group: 'board',
    title: 'Communications Chair',
    name: 'Tyler Brooks',
    role: 'Manages social media and external communications',
    photoUrl: 'https://images.unsplash.com/photo-1519345182560-3f2917c472ef?w=400&h=400&fit=crop',
    order: 8,
    active: true,
    bio: 'Digital marketing specialist amplifying our club\'s voice.',
  },
]

// ============================================================================
// EVENTS - Variety of types (Free, Paid, Zoom, Hybrid, Service)
// ============================================================================
export const TEST_EVENTS = [
  // FREE VIRTUAL EVENT (Zoom)
  {
    id: 'test-zoom-general-meeting',
    title: 'Virtual General Meeting - January',
    category: 'upcoming',
    eventType: 'free',
    venueType: 'virtual',
    description: 'Join us for our monthly virtual general meeting! We\'ll discuss upcoming projects, vote on initiatives, and hear updates from committee chairs. All members welcome - grab your coffee and log in!',
    location: 'Zoom',
    virtualLink: 'https://zoom.us/j/123456789',
    startDate: daysFromNow(3).toISOString().split('T')[0],
    startTime: '19:00',
    endDate: daysFromNow(3).toISOString().split('T')[0],
    endTime: '21:00',
    timezone: 'America/New_York',
    visibility: 'member',
    requiresRegistration: true,
    allowGuests: false,
    capacity: 100,
    imageUrl: 'https://images.unsplash.com/photo-1587825140708-dfaf72ae4b04?w=1200&h=630&fit=crop',
    tags: ['meeting', 'virtual', 'monthly'],
    status: 'published',
    order: 1,
  },
  // FREE IN-PERSON EVENT
  {
    id: 'test-free-networking-happy-hour',
    title: 'Networking Happy Hour',
    category: 'upcoming',
    eventType: 'free',
    venueType: 'physical',
    description: 'Casual networking event for members and prospective members. Come meet fellow young professionals, make connections, and learn about upcoming Rotaract opportunities. First drink on us for new guests!',
    location: 'The Ainsworth, 122 W 26th St, New York, NY 10001',
    startDate: daysFromNow(7).toISOString().split('T')[0],
    startTime: '18:00',
    endDate: daysFromNow(7).toISOString().split('T')[0],
    endTime: '20:00',
    timezone: 'America/New_York',
    visibility: 'public',
    requiresRegistration: true,
    allowGuests: true,
    capacity: 50,
    imageUrl: 'https://images.unsplash.com/photo-1543007630-9710e4a00a20?w=1200&h=630&fit=crop',
    tags: ['networking', 'social', 'happy-hour'],
    status: 'published',
    order: 2,
  },
  // PAID EVENT - Gala/Fundraiser
  {
    id: 'test-paid-winter-gala',
    title: 'Winter Charity Gala 2026',
    category: 'upcoming',
    eventType: 'paid',
    venueType: 'physical',
    description: 'Join us for an elegant evening of giving! Our annual Winter Gala features a cocktail reception, silent auction, live entertainment, and dinner. All proceeds benefit NYC youth education programs. Black tie optional.',
    location: 'The Plaza Hotel, 768 5th Ave, New York, NY 10019',
    startDate: daysFromNow(45).toISOString().split('T')[0],
    startTime: '18:30',
    endDate: daysFromNow(45).toISOString().split('T')[0],
    endTime: '23:00',
    timezone: 'America/New_York',
    visibility: 'public',
    requiresRegistration: true,
    allowGuests: true,
    capacity: 200,
    memberPrice: 85,
    memberEarlyBirdPrice: 65,
    guestPrice: 125,
    guestEarlyBirdPrice: 100,
    earlyBirdDeadline: daysFromNow(30).toISOString().split('T')[0],
    registrationDeadline: daysFromNow(43).toISOString().split('T')[0],
    imageUrl: 'https://images.unsplash.com/photo-1519671482749-fd09be7ccebf?w=1200&h=630&fit=crop',
    tags: ['gala', 'fundraiser', 'charity', 'formal'],
    status: 'published',
    order: 3,
  },
  // PAID EVENT - Workshop
  {
    id: 'test-paid-leadership-workshop',
    title: 'Leadership Excellence Workshop',
    category: 'upcoming',
    eventType: 'paid',
    venueType: 'hybrid',
    description: 'Intensive half-day workshop on leadership skills, featuring executive coaches and interactive sessions. Topics include: emotional intelligence, strategic thinking, public speaking, and team management. Certificate provided.',
    location: 'WeWork Times Square, 1460 Broadway, New York, NY',
    virtualLink: 'https://zoom.us/j/987654321',
    startDate: daysFromNow(21).toISOString().split('T')[0],
    startTime: '09:00',
    endDate: daysFromNow(21).toISOString().split('T')[0],
    endTime: '13:00',
    timezone: 'America/New_York',
    visibility: 'public',
    requiresRegistration: true,
    allowGuests: true,
    capacity: 40,
    memberPrice: 35,
    guestPrice: 55,
    imageUrl: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=1200&h=630&fit=crop',
    tags: ['workshop', 'leadership', 'professional-development'],
    status: 'published',
    order: 4,
  },
  // SERVICE EVENT (tracks hours)
  {
    id: 'test-service-food-bank',
    title: 'Food Bank Volunteer Day',
    category: 'upcoming',
    eventType: 'service',
    venueType: 'physical',
    description: 'Help sort and pack food donations at the Food Bank for NYC. Gloves and supplies provided. Wear comfortable clothes and closed-toe shoes. This is a great way to give back while earning service hours!',
    location: 'Food Bank For New York City, 39 Broadway, New York, NY 10006',
    startDate: daysFromNow(10).toISOString().split('T')[0],
    startTime: '10:00',
    endDate: daysFromNow(10).toISOString().split('T')[0],
    endTime: '14:00',
    timezone: 'America/New_York',
    visibility: 'member',
    requiresRegistration: true,
    allowGuests: true,
    capacity: 25,
    serviceHours: 4,
    serviceDescription: 'Food sorting and packing for NYC families in need',
    imageUrl: 'https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?w=1200&h=630&fit=crop',
    tags: ['service', 'volunteer', 'food-bank'],
    status: 'published',
    order: 5,
  },
  // SERVICE EVENT - Environmental
  {
    id: 'test-service-park-cleanup',
    title: 'Central Park Spring Cleanup',
    category: 'upcoming',
    eventType: 'service',
    venueType: 'physical',
    description: 'Join fellow Rotaractors for our annual spring cleanup in Central Park! We\'ll be removing litter, planting flowers, and beautifying the Conservatory Garden. All supplies provided. Families welcome!',
    location: 'Central Park Conservatory Garden, 5th Ave & 105th St',
    startDate: daysFromNow(28).toISOString().split('T')[0],
    startTime: '09:00',
    endDate: daysFromNow(28).toISOString().split('T')[0],
    endTime: '12:00',
    timezone: 'America/New_York',
    visibility: 'public',
    requiresRegistration: true,
    allowGuests: true,
    capacity: 40,
    serviceHours: 3,
    serviceDescription: 'Park cleanup and beautification',
    imageUrl: 'https://images.unsplash.com/photo-1567095761054-7a02e69e5c43?w=1200&h=630&fit=crop',
    tags: ['service', 'environment', 'cleanup'],
    status: 'published',
    order: 6,
  },
  // PAST EVENT
  {
    id: 'test-past-holiday-party',
    title: 'Holiday Party 2025',
    category: 'past',
    eventType: 'paid',
    venueType: 'physical',
    description: 'Our festive holiday celebration brought together 150+ members and guests for an unforgettable evening of food, music, and holiday cheer. Thank you to everyone who attended!',
    location: 'The Campbell, 15 Vanderbilt Ave, New York, NY',
    startDate: '2025-12-15',
    startTime: '19:00',
    endDate: '2025-12-15',
    endTime: '23:00',
    timezone: 'America/New_York',
    visibility: 'public',
    requiresRegistration: true,
    memberPrice: 45,
    guestPrice: 65,
    imageUrl: 'https://images.unsplash.com/photo-1482517967863-00e15c9b44be?w=1200&h=630&fit=crop',
    tags: ['holiday', 'party', 'social'],
    status: 'published',
    order: 1,
  },
]

// ============================================================================
// ARTICLES / BLOG POSTS
// ============================================================================
export const TEST_ARTICLES = [
  {
    slug: 'member-spotlight-alexandra-rivera',
    title: 'Member Spotlight: Alexandra Rivera on Leadership and Service',
    date: 'January 2026',
    author: 'Tyler Brooks',
    category: 'Club News',
    excerpt: 'Get to know our new Club President and her vision for Rotaract NYC in 2026.',
    content: [
      'Every great club needs great leadership, and we\'re thrilled to introduce Alexandra Rivera as our 2026 Club President.',
      'Alexandra joined Rotaract NYC five years ago as a young finance professional looking to give back to her community. Since then, she\'s led our Service Committee, organized multiple fundraising campaigns, and mentored dozens of new members.',
      '"Rotaract has given me skills I never learned in business school," Alexandra shares. "Public speaking, project management, conflict resolution - these are things you can only learn by doing."',
      'Her vision for 2026 focuses on three pillars: expanding our community partnerships, launching a formal mentorship program, and increasing member engagement through innovative events.',
      '"I want every member to feel like they have a home here," she says. "Whether you\'re looking for professional development, service opportunities, or just a great group of friends, Rotaract NYC has something for you."',
    ],
    imageUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=1200&h=630&fit=crop',
    readTime: '5 min read',
    published: true,
  },
  {
    slug: 'winter-gala-announcement',
    title: 'Save the Date: Winter Charity Gala 2026',
    date: 'January 2026',
    author: 'Sofia Martinez',
    category: 'Events',
    excerpt: 'Mark your calendars for our biggest fundraising event of the year - the Winter Charity Gala!',
    content: [
      'We are excited to announce our annual Winter Charity Gala, taking place at the iconic Plaza Hotel on March 11th, 2026.',
      'This year\'s gala will support youth education programs across New York City, with a goal of raising $50,000 for scholarships and after-school programs.',
      'The evening will feature a cocktail reception, silent auction with items donated by local businesses and members, live entertainment by the Jazz at Lincoln Center Orchestra, and a three-course dinner.',
      'Early bird tickets are available now at a special rate for members. Don\'t miss this opportunity to dress up, network with fellow young professionals, and make a real difference in our community.',
      'Sponsorship opportunities are also available for businesses and individuals who want to increase their impact. Contact our Events Committee for more information.',
    ],
    imageUrl: 'https://images.unsplash.com/photo-1519671482749-fd09be7ccebf?w=1200&h=630&fit=crop',
    readTime: '4 min read',
    published: true,
  },
  {
    slug: 'service-hours-program-launch',
    title: 'New Service Hours Tracking Program Launches',
    date: 'January 2026',
    author: 'Amara Okonkwo',
    category: 'Service',
    excerpt: 'Track your volunteer hours, earn recognition, and see your impact with our new service tracking system.',
    content: [
      'We\'re proud to announce the launch of our new Service Hours Tracking Program, designed to help members log their volunteer contributions and see the collective impact of Rotaract NYC.',
      'The new system, integrated into our member portal, allows you to log service hours from club events and personal volunteer activities, track your progress toward annual goals, view club-wide impact statistics, and earn badges and recognition for milestones.',
      '"We wanted to make it easy for members to see how their individual contributions add up to something bigger," explains Service Chair Amara Okonkwo.',
      'In 2025, our club collectively contributed over 2,500 service hours to the NYC community. With this new tracking system, we\'re aiming to increase that by 25% in 2026.',
      'Log in to your member portal to start tracking your hours today!',
    ],
    imageUrl: 'https://images.unsplash.com/photo-1559027615-cd4628902d4a?w=1200&h=630&fit=crop',
    readTime: '3 min read',
    published: true,
  },
  {
    slug: 'professional-development-series-2026',
    title: 'Announcing Our 2026 Professional Development Series',
    date: 'January 2026',
    author: 'Marcus Thompson',
    category: 'Professional',
    excerpt: 'A year-long series of workshops, panels, and networking events to boost your career.',
    content: [
      'We\'re kicking off 2026 with an ambitious Professional Development Series designed to help members advance their careers while building meaningful connections.',
      'The series includes monthly workshops on topics like salary negotiation, personal branding, and leadership skills. We\'ll also host quarterly industry panels featuring executives from finance, tech, healthcare, and non-profit sectors.',
      'February\'s workshop will focus on "Building Your Personal Brand in the Digital Age," featuring guest speaker Maria Rodriguez, VP of Marketing at a leading tech company.',
      'All workshops will be offered in hybrid format, with both in-person and virtual attendance options. Members receive priority registration and discounted pricing.',
      'Stay tuned to our events calendar for the full schedule and registration links.',
    ],
    imageUrl: 'https://images.unsplash.com/photo-1551135049-8a33b5883817?w=1200&h=630&fit=crop',
    readTime: '4 min read',
    published: true,
  },
  {
    slug: 'year-in-review-2025',
    title: 'Year in Review: Rotaract NYC\'s 2025 Impact',
    date: 'December 2025',
    author: 'Jennifer Park',
    category: 'Club News',
    excerpt: 'A look back at everything our club accomplished in 2025 - the numbers, the stories, and the memories.',
    content: [
      'As we close out 2025, let\'s celebrate the incredible impact our members made this year.',
      'By the numbers: 2,500+ service hours contributed, $35,000 raised for charity, 45 events hosted, 28 new members welcomed.',
      'Highlights included our partnership with the Food Bank for NYC, where we packed over 10,000 meals. Our Holiday Charity Drive collected donations for 100+ families. And our mentorship program connected 30 young professionals with established leaders.',
      'But the numbers only tell part of the story. This year was about connections - new friendships formed at happy hours, professional advice shared over coffee, and the satisfaction of knowing we\'re making a difference together.',
      'Thank you to every member who showed up, volunteered, donated, and made Rotaract NYC what it is. Here\'s to an even more impactful 2026!',
    ],
    imageUrl: 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=1200&h=630&fit=crop',
    readTime: '5 min read',
    published: true,
  },
]

// ============================================================================
// PORTAL DOCUMENTS / RESOURCES
// ============================================================================
export const TEST_DOCUMENTS = [
  {
    id: 'doc-member-handbook-2026',
    title: 'Member Handbook 2026',
    category: 'Governance',
    description: 'Complete guide for members including club policies, committees, and how to get involved.',
    url: 'https://example.com/handbook-2026.pdf',
    visibility: 'member',
    fileSize: '2.4 MB',
    fileType: 'pdf',
  },
  {
    id: 'doc-club-bylaws',
    title: 'Club Bylaws (Revised 2025)',
    category: 'Governance',
    description: 'Official club bylaws governing membership, elections, and operations.',
    url: 'https://example.com/bylaws-2025.pdf',
    visibility: 'member',
    fileSize: '856 KB',
    fileType: 'pdf',
  },
  {
    id: 'doc-brand-guidelines',
    title: 'Brand & Logo Guidelines',
    category: 'Marketing',
    description: 'Official Rotaract NYC branding guidelines, logo files, and usage rules.',
    url: 'https://example.com/brand-guide.pdf',
    visibility: 'member',
    fileSize: '5.1 MB',
    fileType: 'pdf',
  },
  {
    id: 'doc-meeting-minutes-jan-2026',
    title: 'General Meeting Minutes - January 2026',
    category: 'Minutes',
    description: 'Official minutes from the January 2026 general meeting.',
    url: 'https://example.com/minutes-jan-2026.pdf',
    visibility: 'member',
    fileSize: '245 KB',
    fileType: 'pdf',
  },
  {
    id: 'doc-treasurer-report-q4-2025',
    title: 'Treasurer Report Q4 2025',
    category: 'Finance',
    description: 'Quarterly financial report including income, expenses, and budget status.',
    url: 'https://example.com/treasurer-q4-2025.pdf',
    visibility: 'board',
    fileSize: '512 KB',
    fileType: 'pdf',
  },
  {
    id: 'doc-service-project-template',
    title: 'Service Project Planning Template',
    category: 'Templates',
    description: 'Template for planning and documenting service projects. Includes checklist and budget tracker.',
    url: 'https://example.com/service-template.xlsx',
    visibility: 'member',
    fileSize: '89 KB',
    fileType: 'xlsx',
  },
  {
    id: 'doc-new-member-checklist',
    title: 'New Member Onboarding Checklist',
    category: 'Onboarding',
    description: 'Step-by-step guide for new members to get started with Rotaract NYC.',
    url: 'https://example.com/onboarding-checklist.pdf',
    visibility: 'member',
    fileSize: '156 KB',
    fileType: 'pdf',
  },
]

// ============================================================================
// ANNOUNCEMENTS / NOTES
// ============================================================================
export const TEST_ANNOUNCEMENTS = [
  {
    id: 'ann-welcome-2026',
    title: 'Welcome to 2026!',
    body: 'Happy New Year, Rotaract NYC! We have an exciting year planned with new events, service opportunities, and professional development programs. Check out our events calendar and mark your favorites. Here\'s to another year of Service Above Self!',
    pinned: true,
    visibility: 'member',
    createdBy: 'president-2026',
  },
  {
    id: 'ann-dues-reminder',
    title: 'Annual Dues Reminder',
    body: 'Friendly reminder that 2026 annual dues are now due. Dues help fund our service projects, events, and club operations. Pay online through the member portal or contact our Treasurer for payment options. Thank you for your continued support!',
    pinned: true,
    visibility: 'member',
    createdBy: 'treasurer-2026',
  },
  {
    id: 'ann-gala-volunteers',
    title: 'Volunteers Needed: Winter Gala',
    body: 'We\'re looking for volunteers to help with our Winter Charity Gala! Roles include registration, silent auction, and event setup. Volunteers receive free admission. Sign up through the events page or contact Sofia Martinez.',
    pinned: false,
    visibility: 'member',
    createdBy: 'events-chair-2026',
  },
  {
    id: 'ann-committee-signup',
    title: 'Join a Committee!',
    body: 'Want to get more involved? We have openings on all committees: Service, Events, Membership, Communications, and Professional Development. Committee members gain leadership experience and help shape club direction. Express interest through the portal!',
    pinned: false,
    visibility: 'member',
    createdBy: 'vice-president-2026',
  },
  {
    id: 'ann-social-media-feature',
    title: 'Featured on Rotary International!',
    body: 'Exciting news! Our Central Park Cleanup project was featured on Rotary International\'s social media channels. Great job to everyone who participated - you\'re making NYC proud! Check out the feature on our Instagram.',
    pinned: false,
    visibility: 'member',
    createdBy: 'communications-chair-2026',
  },
]

// ============================================================================
// COMMUNITY POSTS (for portal feed)
// ============================================================================
export const TEST_COMMUNITY_POSTS = [
  {
    id: 'cpost-gala-prep',
    authorUid: 'events-chair-2026',
    authorName: 'Sofia Martinez',
    authorRole: 'Events Chair',
    authorPhotoURL: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200&h=200&fit=crop',
    title: 'Gala Planning Update',
    body: 'Just finished the venue walkthrough at The Plaza - it\'s going to be AMAZING! Can\'t wait to share more details soon. Who\'s excited? 🎉',
    type: 'text',
    images: null,
    document: null,
    likesCount: 34,
    commentsCount: 12,
  },
  {
    id: 'cpost-food-bank-photos',
    authorUid: 'service-chair-2026',
    authorName: 'Amara Okonkwo',
    authorRole: 'Service Chair',
    authorPhotoURL: 'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=200&h=200&fit=crop',
    title: 'Last Week\'s Food Bank Volunteer Day',
    body: 'What an incredible turnout! 22 members showed up and we packed over 800 meal kits. Thank you to everyone who gave their Saturday morning to help NYC families. Photos attached! 📸',
    type: 'image',
    images: [
      'https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1593113598332-cd288d649433?w=800&h=600&fit=crop',
    ],
    document: null,
    likesCount: 56,
    commentsCount: 18,
  },
  {
    id: 'cpost-job-opportunity',
    authorUid: 'u_member_1',
    authorName: 'Michael Torres',
    authorRole: 'Member',
    authorPhotoURL: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=200&h=200&fit=crop',
    title: 'Job Opportunity Alert!',
    body: 'My company is hiring a Marketing Manager - great opportunity for someone with 3-5 years experience. DM me if interested and I\'ll refer you! #RotaractNetwork',
    type: 'text',
    images: null,
    document: null,
    likesCount: 28,
    commentsCount: 8,
  },
  {
    id: 'cpost-minutes-upload',
    authorUid: 'secretary-2026',
    authorName: 'Jennifer Park',
    authorRole: 'Club Secretary',
    authorPhotoURL: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&h=200&fit=crop',
    title: null,
    body: 'January meeting minutes are now available in the Documents section. Please review before the next meeting!',
    type: 'document',
    images: null,
    document: {
      name: 'Meeting_Minutes_Jan_2026.pdf',
      size: '245 KB',
      url: 'https://example.com/minutes-jan-2026.pdf',
    },
    likesCount: 15,
    commentsCount: 2,
  },
]

// ============================================================================
// PORTAL USERS (Sample Members)
// ============================================================================
export const TEST_PORTAL_USERS = [
  {
    uid: 'u_member_1',
    name: 'Michael Torres',
    email: 'michael.t@example.com',
    photoURL: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=200&h=200&fit=crop',
    role: 'MEMBER',
    status: 'active',
    committee: 'Professional Development',
    phoneOptIn: true,
    joinDate: '2024-06-15',
  },
  {
    uid: 'u_member_2',
    name: 'Emily Watson',
    email: 'emily.w@example.com',
    photoURL: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop',
    role: 'MEMBER',
    status: 'active',
    committee: 'Service',
    phoneOptIn: false,
    joinDate: '2023-09-01',
  },
  {
    uid: 'u_member_3',
    name: 'James Kim',
    email: 'james.k@example.com',
    photoURL: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop',
    role: 'MEMBER',
    status: 'active',
    committee: 'Events',
    phoneOptIn: true,
    joinDate: '2025-01-10',
  },
  {
    uid: 'u_member_4',
    name: 'Sarah Johnson',
    email: 'sarah.j@example.com',
    photoURL: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&h=200&fit=crop',
    role: 'MEMBER',
    status: 'active',
    committee: 'Membership',
    phoneOptIn: false,
    joinDate: '2024-03-20',
  },
  {
    uid: 'u_member_5',
    name: 'Chris Anderson',
    email: 'chris.a@example.com',
    photoURL: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&h=200&fit=crop',
    role: 'MEMBER',
    status: 'pending',
    committee: null,
    phoneOptIn: false,
    joinDate: '2026-01-20',
  },
]

// Export all test data
export const ALL_TEST_DATA = {
  teamMembers: TEST_TEAM_MEMBERS,
  events: TEST_EVENTS,
  articles: TEST_ARTICLES,
  documents: TEST_DOCUMENTS,
  announcements: TEST_ANNOUNCEMENTS,
  communityPosts: TEST_COMMUNITY_POSTS,
  portalUsers: TEST_PORTAL_USERS,
}
